kind: Service
apiVersion: v1
metadata:
  name: app-demo
  namespace: demo
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: app-demo
